config/routes.rb
NuggetMgr::Application.routes.draw do
  root :to => 'nuggets#index'
  resources :nuggets
  get "nuggets/index"

  

end

app/models/nugget.rb
class Nugget < ActiveRecord::Base
	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/nuggets_controller.rb
class NuggetsController < ApplicationController
  def index
  	@nugget = Nugget.new
  	@nuggets = Nugget.all
  end

  def create
  	#render :text => params[:nugget].inspect
  	Nugget.create nugget_params
  	redirect_to :back 

  end

  def edit
  	@nugget = Nugget.find params[:id]
  end

  def update
  	@nugget = Nugget.find params[:id]
  	if @nugget.update_attributes nugget_params
  		flash[:notice_good] = 'You nugget was successfully updated!'
  		redirect_to nuggets_path
  	else
  		flash[:notice_bad] = 'There was an error updating your nugget!'
  		redirect_to :back
  	end
  end

  def destroy
  	Nugget.destroy params[:id]
  	flash[:notice_good] = "Nugget successfully deleted."
  	redirect_to :back
  end


  private


  # WHY???
  def nugget_params
    allow = [:name, :description, :markForReview]
    params.require(:nugget).permit(allow)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nuggets_helper.rb
module NuggetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NuggetMgr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, message| %>
	<div id="flash_<%= name %>">
		<%= message %>
	</div>
<% end %>

<%= yield %>

</body>
</html>

app/views/nuggets/_form.html.erb
<%= form_for @nugget do |f| %>
	<table>
		<tr>
			<td>
				<%= f.label :name %> 
			</td>
			<td>
				<%= f.text_field :name %> 
			</td>
		</tr>
		<tr>
			<td>
				<%= f.label :description %>
			</td>
			<td>
				<%= f.text_area :description %> 
			</td>
		</tr>
		<tr>
			<td>
				<%= f.label "Mark for review" %>
			</td>
			<td>
				<%= f.check_box :markForReview %>
			</td>
		</tr>
	</table>
	<%= f.submit %>
<% end %>

app/views/nuggets/edit.html.erb
<h1>Edit Nugget</h1>
<%= render 'form' %>

app/views/nuggets/index.html.erb
<h1>Nuggets</h1>

<table border="1">
		<tr>
			<td>Name</td>
			<td>Description</td>
			<td>Tags</td>
			<td>Marked for Review?</td>
		</tr>
	<% for nugget in @nuggets %>
		<tr>
			<td> <%= nugget.name %> </td>
			<td> <%= nugget.description %> </td>
			<td> <%= nugget.tags %> </td>
			<td> <%= nugget.markForReview %> </td>
			<td> <%= link_to 'Edit', edit_nugget_path(nugget) %> </td>		
			<td> <%= link_to 'Delete', nugget, :method => 'delete' %> </td>		
		</tr>
	<% end %>
</table>

<h2>Add New Nugget</h2>

<%= render 'form' %>